const {
  CLOCKING_SYSTEM_NODE_ENV,
  CLOCKING_SYSTEM_TEST_PORT,
  CLOCKING_SYSTEM_TEST_DATABASE_URL,
  CLOCKING_SYSTEM_TEST_ALLOWABLE_ORIGINS
} = process.env;

export default {
  CLOCKING_SYSTEM_NODE_ENV,
  CLOCKING_SYSTEM_PORT: CLOCKING_SYSTEM_TEST_PORT,
  CLOCKING_SYSTEM_DATABASE_URL: CLOCKING_SYSTEM_TEST_DATABASE_URL,
  CLOCKING_SYSTEM_ALLOWABLE_ORIGINS: CLOCKING_SYSTEM_TEST_ALLOWABLE_ORIGINS
};
